In [3]:
import pandas as pd
from pathlib import Path
import statistics
import matplotlib.pyplot as plt
import numpy as np
pd.plotting.register_matplotlib_converters()
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from datetime import timedelta
import plotly.express as px

In [4]:
df=pd.read_csv('C:/Users/euzoe/OneDrive/Desktop/DATA ANALYSIS/MY_PROJECTS/AppleStore.csv')
df.head()

,id,track_name,size_bytes,currency,price,rating_count_tot,rating_count_ver,user_rating,user_rating_ver,ver,cont_rating,prime_genre,sup_devices.num,ipadSc_urls.num,lang.num,vpp_lic
0,284882215,Facebook,389879808,USD,0.0,2974676,212,3.5,3.5,95.0,4+,Social Networking,37,1,29,1
1,389801252,Instagram,113954816,USD,0.0,2161558,1289,4.5,4.0,10.23,12+,Photo & Video,37,0,29,1
2,529479190,Clash of Clans,116476928,USD,0.0,2130805,579,4.5,4.5,9.24.12,9+,Games,38,5,18,1
3,420009108,Temple Run,65921024,USD,0.0,1724546,3842,4.5,4.0,1.6.2,9+,Games,40,5,1,1
4,284035177,Pandora - Music & Radio,130242560,USD,0.0,1126879,3594,4.0,4.5,8.4.1,12+,Music,37,4,1,1

In [36]:
df.shape

(7197, 16)

In [53]:
fil=df.loc[df['user_rating_ver'] >= 5]

In [57]:
fil.groupby(['track_name']) [['user_rating_ver']].max().sort_values(by=['user_rating_ver'], ascending=False).reset_index()

                              track_name  user_rating_ver
0                                 "HOOK"              5.0
1                        SayHi Translate              5.0
2                     Sky Force Reloaded              5.0
3     Sky Guide: View Stars Night or Day              5.0
4                    SkyDroid - Golf GPS              5.0
..                                   ...              ...
959                            Headspace              5.0
960  Heuristic Shakespeare - The Tempest              5.0
961                     Hide it Hillary!              5.0
962               Highlights Monster Day              5.0
963                    鬼畜-一亿人都在用的聊天必备神器!              5.0

[964 rows x 2 columns]